import { Product } from "@/types/product.type";

export const products: Product[] = [
    {
        id: 1,
        name: "Pc",
        price: 500,
        category: "electronic",
        imgSrc: "https://images.unsplash.com/photo-1560131914-2e469a0e8607?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTQyNjF8MHwxfGFsbHx8fHx8fHx8fDE3MzYyNDg5NjF8&ixlib=rb-4.0.3&q=80&w=1080",
    },
    {
        id: 2,
        name: "Smartphone",
        price: 700,
        category: "electronic",
        imgSrc: "https://via.placeholder.com/400x300/4CAF50/FFFFFF?text=Smartphone",
    },
    {
        id: 3,
        name: "Treadmill",
        price: 1200,
        category: "fitness",
        imgSrc: "https://via.placeholder.com/400x300/2196F3/FFFFFF?text=Treadmill",
    },
    {
        id: 4,
        name: "Running Shoes",
        price: 100,
        category: "fitness",
        imgSrc: "https://via.placeholder.com/400x300/FFC107/FFFFFF?text=Running+Shoes",
    },
    {
        id: 5,
        name: "Jacket",
        price: 80,
        category: "clothing",
        imgSrc: "https://via.placeholder.com/400x300/9C27B0/FFFFFF?text=Jacket",
    },
    {
        id: 6,
        name: "Jeans",
        price: 60,
        category: "clothing",
        imgSrc: "https://via.placeholder.com/400x300/3F51B5/FFFFFF?text=Jeans",
    },
    {
        id: 7,
        name: "Lipstick",
        price: 20,
        category: "cosmetic",
        imgSrc: "https://via.placeholder.com/400x300/E91E63/FFFFFF?text=Lipstick",
    },
    {
        id: 8,
        name: "Shampoo",
        price: 10,
        category: "cosmetic",
        imgSrc: "https://via.placeholder.com/400x300/673AB7/FFFFFF?text=Shampoo",
    },
    {
        id: 9,
        name: "Gaming Mouse",
        price: 50,
        category: "gaming",
        imgSrc: "https://via.placeholder.com/400x300/009688/FFFFFF?text=Gaming+Mouse",
    },
    {
        id: 10,
        name: "Keyboard",
        price: 80,
        category: "gaming",
        imgSrc: "https://via.placeholder.com/400x300/8BC34A/FFFFFF?text=Keyboard",
    },
    {
        id: 11,
        name: "Laptop",
        price: 1000,
        category: "electronic",
        imgSrc: "https://via.placeholder.com/400x300/F44336/FFFFFF?text=Laptop",
    },
    {
        id: 12,
        name: "Smartwatch",
        price: 200,
        category: "electronic",
        imgSrc: "https://via.placeholder.com/400x300/FF5722/FFFFFF?text=Smartwatch",
    },
    {
        id: 13,
        name: "Yoga Mat",
        price: 40,
        category: "fitness",
        imgSrc: "https://via.placeholder.com/400x300/00BCD4/FFFFFF?text=Yoga+Mat",
    },
    {
        id: 14,
        name: "Sweater",
        price: 45,
        category: "clothing",
        imgSrc: "https://via.placeholder.com/400x300/607D8B/FFFFFF?text=Sweater",
    },
    {
        id: 15,
        name: "Moisturizer",
        price: 25,
        category: "cosmetic",
        imgSrc: "https://via.placeholder.com/400x300/795548/FFFFFF?text=Moisturizer",
    },
    {
        id: 16,
        name: "Headset",
        price: 150,
        category: "gaming",
        imgSrc: "https://via.placeholder.com/400x300/607D8B/FFFFFF?text=Headset",
    },
    {
        id: 17,
        name: "Monitor",
        price: 300,
        category: "electronic",
        imgSrc: "https://via.placeholder.com/400x300/FF9800/FFFFFF?text=Monitor",
    },
    {
        id: 18,
        name: "Skincare Set",
        price: 60,
        category: "cosmetic",
        imgSrc: "https://via.placeholder.com/400x300/8D6E63/FFFFFF?text=Skincare+Set",
    },
    {
        id: 19,
        name: "Controller",
        price: 40,
        category: "gaming",
        imgSrc: "https://via.placeholder.com/400x300/FFC107/FFFFFF?text=Controller",
    },
    {
        id: 20,
        name: "Fitness Tracker",
        price: 120,
        category: "fitness",
        imgSrc: "https://via.placeholder.com/400x300/009688/FFFFFF?text=Fitness+Tracker",
    },
] as const;
