import { Product } from "@/types/product.type";

export const products: Product[] = [
    {
        id: 1,
        name: "PC",
        price: 500,
        category: "electronic",
        imgSrc: "https://images.unsplash.com/photo-1560131914-2e469a0e8607?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2OTQyNjF8MHwxfGFsbHx8fHx8fHx8fDE3MzYyNDg5NjF8&ixlib=rb-4.0.3&q=80&w=1080",
    },
    {
        id: 2,
        name: "Smartphone",
        price: 700,
        category: "electronic",
        imgSrc: "https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/region/global/products/smartphones/tcl-50-nxtpaper-5g/id-images/1.png?t=1721373014838&w=800",
    },
    {
        id: 3,
        name: "Treadmill",
        price: 1200,
        category: "fitness",
        imgSrc: "https://webapi-prod.technogym.com/dw/image/v2/BFLQ_PRD/on/demandware.static/-/Sites-tg-catalog-master/default/dwfa987005/product/DCKA/technogym_myrun_gallery_001.jpg?sw=1840&sh=1380",
    },
    {
        id: 4,
        name: "Running Shoes",
        price: 100,
        category: "fitness",
        imgSrc: "https://trere-uyn.b-cdn.net/products/images/ecomm_SX4_Y100311_A140_front.jpg-1200x1200.jpeg",
    },

    {
        id: 5,
        name: "Jacket",
        price: 80,
        category: "clothing",
        imgSrc: "https://placehold.co/150x150/FFA500/000000.png?text=Jacket",
    },
    {
        id: 6,
        name: "Jeans",
        price: 60,
        category: "clothing",
        imgSrc: "https://placehold.co/150x150/FFA500/000000.png?text=Jeans",
    },
    {
        id: 7,
        name: "Lipstick",
        price: 20,
        category: "cosmetic",
        imgSrc: "https://placehold.co/150x150/FFC0CB/000000.png?text=Lipstick",
    },
    {
        id: 8,
        name: "Shampoo",
        price: 10,
        category: "cosmetic",
        imgSrc: "https://placehold.co/150x150/FFC0CB/000000.png?text=Shampoo",
    },
    {
        id: 9,
        name: "Gaming Mouse",
        price: 50,
        category: "gaming",
        imgSrc: "https://placehold.co/150x150/ADD8E6/000000.png?text=Gaming+Mouse",
    },
    {
        id: 10,
        name: "Keyboard",
        price: 80,
        category: "gaming",
        imgSrc: "https://placehold.co/150x150/ADD8E6/000000.png?text=Keyboard",
    },
    {
        id: 11,
        name: "Laptop",
        price: 1000,
        category: "electronic",
        imgSrc: "https://placehold.co/150x150/D3D3D3/000000.png?text=Laptop",
    },
    {
        id: 12,
        name: "Smartwatch",
        price: 200,
        category: "electronic",
        imgSrc: "https://placehold.co/150x150/D3D3D3/000000.png?text=Smartwatch",
    },
    {
        id: 13,
        name: "Yoga Mat",
        price: 40,
        category: "fitness",
        imgSrc: "https://placehold.co/150x150/98FB98/000000.png?text=Yoga+Mat",
    },
    {
        id: 14,
        name: "Sweater",
        price: 45,
        category: "clothing",
        imgSrc: "https://placehold.co/150x150/FFA500/000000.png?text=Sweater",
    },
    {
        id: 15,
        name: "Moisturizer",
        price: 25,
        category: "cosmetic",
        imgSrc: "https://placehold.co/150x150/FFC0CB/000000.png?text=Moisturizer",
    },
    {
        id: 16,
        name: "Headset",
        price: 150,
        category: "gaming",
        imgSrc: "https://placehold.co/150x150/ADD8E6/000000.png?text=Headset",
    },
    {
        id: 17,
        name: "Monitor",
        price: 300,
        category: "electronic",
        imgSrc: "https://placehold.co/150x150/D3D3D3/000000.png?text=Monitor",
    },
    {
        id: 18,
        name: "Skincare Set",
        price: 60,
        category: "cosmetic",
        imgSrc: "https://placehold.co/150x150/FFC0CB/000000.png?text=Skincare+Set",
    },
    {
        id: 19,
        name: "Controller",
        price: 40,
        category: "gaming",
        imgSrc: "https://placehold.co/150x150/ADD8E6/000000.png?text=Controller",
    },
    {
        id: 20,
        name: "Fitness Tracker",
        price: 120,
        category: "fitness",
        imgSrc: "https://placehold.co/150x150/98FB98/000000.png?text=Fitness+Tracker",
    },
];
